before_script:
  - apt-get update -qq && apt-get install -y python3
  - python3 --version

deploy:
  script:
    - pkill python3
    - python3 annotation-helper/server.py -H '' -p 8000 -l /tmp/annotation.log --loglevel DEBUG

# vim: sts=2 sw=2 et si
