before_script:
  - yum -y -q update && yum -y -q install python34
  - python3 --version

deploy:
  script:
    - pkill --full annotation-helper && [ $? -le 1 ]
    - python3 annotation-helper/server.py -H '' -p 8000 -l /tmp/annotation.log --loglevel DEBUG

# vim: sts=2 sw=2 et si
