---
# GitLab CI file for a shell runner.
stages:
  - prepare
  - test
  - deploy

python3:
  stage: prepare
  script:
    - 'yum -y -q update && yum -y -q install python34'
    - 'python3 --version'
    - 'pip3 --version || (curl https://bootstrap.pypa.io/get-pip.py | python3.4)'

venv:
  stage: prepare
  variables:
    VIRTUALENV: 'annotation-helper-env/'
    REQUIREMENTS: 'requirements.txt'
    TEST_REQUIREMENTS: 'test/requirements.txt'
  script:
    - 'virtualenv --version || pip3 install virtualenv'
    - 'source "$HOME/$VIRTUALENV/bin/activate" 2>/dev/null || virtualenv -p python3 "$HOME/$VIRTUALENV" && source "$HOME/$VIRTUALENV/bin/activate"'
    - '[ ! -r "$REQUIREMENTS" ] || pip3 install -r "$REQUIREMENTS"'
    - '[ ! -r "$TEST_REQUIREMENTS" ] || pip3 install -r "$TEST_REQUIREMENTS"'

pylint:
  stage: test
  variables:
    MIN_PYLINT_RATING: '7'
  script:
    - 'pip3 install pylint'
    - 'bash test/pylint.sh "$MIN_PYLINT_RATING" || true'

deploy:
  stage: deploy
  variables:
    HOST: ''
    PORT: '8000'
    LOGLEVEL: 'DEBUG'
    LOGFILE: '$HOME/annotation.log'
  script:
    - 'pkill -f -u gitlab-runner annotation-helper && [ $? -le 1 ]'
    - 'python3 annotation-helper/server.py -H "$HOST" -p "$PORT" -l "$HOME/$LOGFILE" --loglevel "$LOGLEVEL" </dev/null >/dev/null 2>&1 &'
