before_script:
  - yum -y -q update && yum -y -q install python34
  - python3 --version

test:
  script:
    - bash test/test.sh

deploy:
  script:
    - pkill -f -u gitlab-runner annotation-helper && [ $? -le 1 ]
    - python3 annotation-helper/server.py -H '' -p 8000 -l ~/annotation.log --loglevel DEBUG </dev/null >/dev/null 2>&1 &

# vim: sts=2 sw=2 et si
